# Generated by Django 6.0.7 on 2026-07-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('dept', models.CharField(max_length=10, null=True)),
                ('credit', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
